[package]
name = "dvine_dylib"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
dvine_internal = { path = "../dvine_internal" }

[lints]
workspace = true
